#!/bin/bash

set -e

[ "$DEBUG" == 'true' ] && set -x

# Ensure /var/lib/mysql is mounted as tmpfs
#if ! mountpoint -q /var/lib/mysql; then
#  echo "Mounting /var/lib/mysql as tmpfs..."
#  mount /var/lib/mysql
#fi

# Initialize MySQL data directory if empty
if [ ! -d "/var/lib/mysql/mysql" ]; then
  echo "Initializing MySQL data directory..."
  mysqld --initialize-insecure --user=mysql --datadir=/var/lib/mysql
fi

/usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf &

# Now wait until mysql is online

retries=10
count=0

while [ $count -lt $retries ]; do
  set +e
  mysql -uroot -e "SELECT 1" > /dev/null 2>&1
  set -e
  if [ $? -eq 0 ]; then
    echo "MySQL is available."
    break
  fi
  count=$((count+1))
  echo "MySQL is not available. Retrying..."
  sleep 1
done

if [ $count -eq $retries ]; then
  echo "Could not connect to MySQL after $retries retries."
  exit 1
fi

# Create databases and users if not already created
echo "Setting up MySQL databases and users..."
mysql -u root -e 'CREATE DATABASE IF NOT EXISTS `magento`;' && \
mysql -u root -e 'CREATE DATABASE IF NOT EXISTS `magento-test`;' && \
mysql -u root -e "CREATE USER IF NOT EXISTS 'magento'@'%' IDENTIFIED WITH mysql_native_password BY 'password';" && \
mysql -u root -e "CREATE USER IF NOT EXISTS 'magento-test'@'%' IDENTIFIED WITH mysql_native_password BY 'password';" && \
mysql -u root -e "GRANT ALL PRIVILEGES ON * . * TO 'magento'@'%';" && \
mysql -u root -e "GRANT ALL PRIVILEGES ON * . * TO 'magento-test'@'%';"

echo "Now connecting to Elasticsearch"
retries=30
count=0

while [ $count -lt $retries ]; do
  if curl -s -f -o /dev/null "http://localhost:9200"; then
    echo "Elasticsearch is available."
    break
  else
    count=$((count+1))
    echo "Attempt $count of $retries: Elasticsearch is not available. Retrying..."
    sleep 1
  fi
done

if [ $count -eq $retries ]; then
  cat /var/log/elasticsearch/elasticsearch.log
  echo "Could not connect to Elasticsearch after $retries retries."
fi
