#!/bin/bash

set -e
[ "$DEBUG" == 'true' ] && set -x

if [ "$COMPOSER_VERSION" == "1" ]; then
  echo "Installing Composer version 1"
  composer self-update --1
fi

/bin/bash -c "/usr/bin/mysqld_safe &"

rm /var/lib/elasticsearch/nodes/node.lock
rm /var/lib/elasticsearch/nodes/*/node.lock

service elasticsearch start

# Now wait until mysql is online

retries=10
count=0

while [ $count -lt $retries ]; do
  mysql -uroot -e "SELECT 1" > /dev/null 2>&1
  if [ $? -eq 0 ]; then
    echo "MySQL is available."
    break
  fi
  count=$((count+1))
  echo "MySQL is not available. Retrying..."
  sleep 1
done

if [ $count -eq $retries ]; then
  echo "Could not connect to MySQL after $retries retries."
fi