#!/bin/bash

set -e

echo "Stopping services..."
/usr/bin/supervisorctl stop elasticsearch
sleep 5
/usr/bin/supervisorctl shutdown

echo "Services stopped."

# Wait until all elasticsearch processes are stopped
count=0
ps aux

rm -fv /var/lib/elasticsearch/nodes/*/node.lock