name: Build base Docker images
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { PHP_VERSION: "8.4", PHP_VERSION_FPM: php84-fpm }
          - { PHP_VERSION: "8.3", PHP_VERSION_FPM: php83-fpm }
          - { PHP_VERSION: "8.2", PHP_VERSION_FPM: php82-fpm }
          - { PHP_VERSION: "8.1", PHP_VERSION_FPM: php81-fpm }
          - { PHP_VERSION: "7.4", PHP_VERSION_FPM: php74-fpm }
          - { PHP_VERSION: "7.3", PHP_VERSION_FPM: php73-fpm }
          - { PHP_VERSION: "7.2", PHP_VERSION_FPM: php72-fpm }
          - { PHP_VERSION: "7.1", PHP_VERSION_FPM: php71-fpm }
    steps:
    - uses: actions/checkout@v4

    # Step 1: Build the docker image
    - name: Build the Docker image
      run:
        docker build .
        -t michielgerritsen/magento2-base-image:${{ matrix.cfg.PHP_VERSION }}
        -t michielgerritsen/magento2-base-image:${{ matrix.cfg.PHP_VERSION_FPM }}
        --build-arg PHP_VERSION=${{ matrix.cfg.PHP_VERSION }}

    - name: Test that the image is working
      run: docker run michielgerritsen/magento2-base-image:${{ matrix.cfg.PHP_VERSION }} ./start-services

    # Step 3: Upload the images to Docker Hub.
    - name: Docker hub login
      if: github.ref == 'refs/heads/main'
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push the image to Docker hub
      if: github.ref == 'refs/heads/main'
      run: docker push michielgerritsen/magento2-base-image:${{ matrix.cfg.PHP_VERSION_FPM }}
