name: Build base Docker images
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { PHP_VERSION: php82-fpm }
          - { PHP_VERSION: php81-fpm }
          - { PHP_VERSION: php80-fpm }
          - { PHP_VERSION: php74-fpm }
          - { PHP_VERSION: php73-fpm }
          - { PHP_VERSION: php72-fpm }
          - { PHP_VERSION: php71-fpm }
    steps:
    - uses: actions/checkout@v1

    # Step 1: Build the docker image
    - name: Build the Docker image
      run:
        docker build .
        -t michielgerritsen/magento2-base-image:${{ matrix.cfg.PHP_VERSION }}
        --build-arg PHP_VERSION=${{ matrix.cfg.PHP_VERSION }}

    # Step 3: Upload the images to Docker Hub.
    - name: Docker hub login
      if: github.ref == 'refs/heads/main'
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push the image to Docker hub
      if: github.ref == 'refs/heads/main'
      run: docker push michielgerritsen/magento2-base-image:${{ matrix.cfg.PHP_VERSION }}
